export const DISH_DETAILS_REQUEST = 'DISH_DETAILS_REQUEST'
export const DISH_DETAILS_SUCCESS = 'DISH_DETAILS_SUCCESS'
export const DISH_DETAILS_FAIL = 'DISH_DETAILS_FAIL'

export const ADD_DISH_REQUEST = 'ADD_DISH_REQUEST'
export const ADD_DISH_SUCCESS = 'ADD_DISH_SUCCESS'
export const ADD_DISH_FAIL = 'ADD_DISH_FAIL'
export const ADD_DISH_RESET = 'ADD_DISH_RESET'

export const UPDATE_DISH_REQUEST = 'UPDATE_DISH_REQUEST'
export const UPDATE_DISH_SUCCESS = 'UPDATE_DISH_SUCCESS'
export const UPDATE_DISH_FAIL = 'UPDATE_DISH_FAIL'
export const UPDATE_DISH_RESET = 'UPDATE_DISH_RESET'