export const ORDER_CREATE_REQUEST = 'ORDER_CREATE_REQUEST'
export const ORDER_CREATE_SUCCESS = 'ORDER_CREATE_SUCCESS'
export const ORDER_CREATE_FAIL = 'ORDER_CREATE_FAIL'

export const ORDER_DETAILS_REQUEST = 'ORDER_DETAILS_REQUEST'
export const ORDER_DETAILS_SUCCESS = 'ORDER_DETAILS_SUCCESS'
export const ORDER_DETAILS_FAIL = 'ORDER_DETAILS_FAIL'

export const GET_USER_ORDERS_REQUEST = 'GET_USER_ORDERS_REQUEST'
export const GET_USER_ORDERS_SUCCESS = 'GET_USER_ORDERS_SUCCESS'
export const GET_USER_ORDERS_FAIL = 'GET_USER_ORDERS_FAIL'

export const GET_RESTAURANT_ORDERS_REQUEST = 'GET_RESTAURANT_ORDERS_REQUEST'
export const GET_RESTAURANT_ORDERS_SUCCESS = 'GET_RESTAURANT_ORDERS_SUCCESS'
export const GET_RESTAURANT_ORDERS_FAIL = 'GET_RESTAURANT_ORDERS_FAIL'

export const ORDER_DELIVER_REQUEST = 'ORDER_DELIVER_REQUEST'
export const ORDER_DELIVER_SUCCESS = 'ORDER_DELIVER_SUCCESS'
export const ORDER_DELIVER_FAIL = 'ORDER_DELIVER_FAIL'
export const ORDER_DELIVER_RESET = 'ORDER_DELIVER_RESET'

export const ORDER_CREATE_RESET = 'ORDER_CREATE_RESET'
