export const RESTAURANT_LIST_REQUEST = 'RESTAURANT_LIST_REQUEST'
export const RESTAURANT_LIST_SUCCESS = 'RESTAURANT_LIST_SUCCESS'
export const RESTAURANT_LIST_FAIL = 'RESTAURANT_LIST_FAIL'

export const RESTAURANT_DETAILS_REQUEST = 'RESTAURANT_DETAILS_REQUEST'
export const RESTAURANT_DETAILS_SUCCESS = 'RESTAURANT_DETAILS_SUCCESS'
export const RESTAURANT_DETAILS_FAIL = 'RESTAURANT_DETAILS_FAIL'


export const RESTAURANT_DISHES_REQUEST = 'RESTAURANT_DISHES_REQUEST'
export const RESTAURANT_DISHES_SUCCESS = 'RESTAURANT_DISHES_SUCCESS'
export const RESTAURANT_DISHES_FAIL = 'RESTAURANT_DISHES_FAIL'

export const RESTAURANT_SIGNUP_REQUEST = 'RESTAURANT_SIGNUP_REQUEST'
export const RESTAURANT_SIGNUP_SUCCESS = 'RESTAURANT_SIGNUP_SUCCESS'
export const RESTAURANT_SIGNUP_FAIL = 'RESTAURANT_SIGNUP_FAIL'
export const RESTAURANT_LOGOUT = 'RESTAURANT_LOGOUT'

export const RESTAURANT_LOGIN_REQUEST = 'RESTAURANT_LOGIN_REQUEST'
export const RESTAURANT_LOGIN_SUCCESS = 'RESTAURANT_LOGIN_SUCCESS'
export const RESTAURANT_LOGIN_FAIL = 'RESTAURANT_LOGIN_FAIL'