export const RESTAURANT_LIST_REQUEST = 'RESTAURANT_LIST_REQUEST'
export const RESTAURANT_LIST_SUCCESS = 'RESTAURANT_LIST_SUCCESS'
export const RESTAURANT_LIST_FAIL = 'RESTAURANT_LIST_FAIL'

export const RESTAURANT_MENU_ITEMS_REQUEST = 'RESTAURANT_MENU_ITEMS_REQUEST'
export const RESTAURANT_MENU_ITEMS_SUCCESS = 'RESTAURANT_MENU_ITEMS_SUCCESS'
export const RESTAURANT_MENU_ITEMS_FAIL = 'RESTAURANT_MENU_ITEMS_FAIL'